# fly.toml app configuration file generated for myfinance-app on 2025-12-11T14:46:25-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "myfinance-app"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  BROADCAST_CONNECTION = 'log'
  CACHE_STORE = 'file'
  DB_CONNECTION = 'sqlite'
  DB_DATABASE = '/data/database.sqlite'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  MAIL_ENCRYPTION = 'tls'
  MAIL_HOST = 'smtp.mailersend.net'
  MAIL_MAILER = 'smtp'
  MAIL_PORT = '587'
  MAIL_FROM_ADDRESS = "MS_3fHVKt@test-z0vklo6897el7qrx.mlsender.net"
  MAIL_FROM_NAME = "MyFinance"
  APP_NAME = "MyFinance"
  QUEUE_CONNECTION = 'sync'
  SESSION_DRIVER = 'cookie'
  # Fix 419 Page Expired & HTTPS
  SESSION_SECURE_COOKIE = "true"
  IS_HTTPS = "true"
  ASSET_URL = "https://myfinance-app.fly.dev"

[[mounts]]
  source = 'myfinance_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
